INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,11);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,12);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,13);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,14);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (22,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (25,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (29,15);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (14,21);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,22);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,22);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,22);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,22);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,22);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,22);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,22);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,22);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (24,22);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (27,23);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,31);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,32);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,33);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (15,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (16,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (17,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (18,34);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,35);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,35);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,35);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,35);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,35);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,35);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,35);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,35);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,35);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,36);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (14,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (15,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (16,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (17,37);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (14,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (15,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (16,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (17,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (90,41);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (28,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (90,42);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (31,43);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (14,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (15,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (16,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (17,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (18,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (19,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (20,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (51,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (52,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (53,44);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (14,45);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,46);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,46);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,46);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,46);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (90,46);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,50);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,50);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (14,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (15,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (16,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (17,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (18,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (19,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (20,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (32,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (33,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (34,51);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,52);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,52);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,52);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,52);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,52);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,52);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (23,52);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (26,52);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (27,52);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (23,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (25,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (26,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (28,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (29,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (31,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (33,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (34,53);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,54);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,54);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,54);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,54);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,54);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,54);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (25,54);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,61);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,61);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,61);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,61);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,61);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,61);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,61);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,61);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,61);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,61);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (10,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (29,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (30,62);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,63);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,63);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (22,63);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (23,63);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (25,63);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (26,63);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (27,63);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (28,63);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,64);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,64);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,64);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,64);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,64);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (23,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (27,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (28,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (29,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (30,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (31,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (32,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (40,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (42,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (43,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (90,65);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (04,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (05,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (06,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (07,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (08,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (09,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (11,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (12,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (13,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (14,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (15,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (17,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (19,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (21,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (24,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (25,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (26,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (27,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (28,71);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,81);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,81);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (03,81);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (01,82);
INSERT INTO `suzz-mini`.`city`(`code`,`fk_province`) VALUES (02,82);


INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='11'),'北京市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='12'),'天津市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='13'),'石家庄市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='13'),'唐山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='13'),'秦皇岛市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='13'),'邯郸市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='13'),'邢台市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='13'),'保定市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='13'),'张家口市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='13'),'承德市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='13'),'沧州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='13'),'廊坊市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='13'),'衡水市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='14'),'太原市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='14'),'大同市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='14'),'阳泉市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='14'),'长治市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='14'),'晋城市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='14'),'朔州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='14'),'晋中市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='14'),'运城市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='14'),'忻州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='14'),'临汾市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='14'),'吕梁市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='15'),'呼和浩特市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='15'),'包头市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='15'),'乌海市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='15'),'赤峰市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='15'),'通辽市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='15'),'鄂尔多斯市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='15'),'呼伦贝尔市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='15'),'巴彦淖尔市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='15'),'乌兰察布市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='22' and fk_province='15'),'兴安盟','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='25' and fk_province='15'),'锡林郭勒盟','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='29' and fk_province='15'),'阿拉善盟','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='21'),'沈阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='21'),'大连市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='21'),'鞍山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='21'),'抚顺市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='21'),'本溪市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='21'),'丹东市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='21'),'锦州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='21'),'营口市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='21'),'阜新市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='21'),'辽阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='21'),'盘锦市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='21'),'铁岭市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='21'),'朝阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='14' and fk_province='21'),'葫芦岛市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='22'),'长春市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='22'),'吉林市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='22'),'四平市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='22'),'辽源市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='22'),'通化市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='22'),'白山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='22'),'松原市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='22'),'白城市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='24' and fk_province='22'),'延边朝鲜族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='23'),'哈尔滨市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='23'),'齐齐哈尔市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='23'),'鸡西市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='23'),'鹤岗市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='23'),'双鸭山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='23'),'大庆市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='23'),'伊春市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='23'),'佳木斯市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='23'),'七台河市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='23'),'牡丹江市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='23'),'黑河市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='23'),'绥化市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='27' and fk_province='23'),'大兴安岭地区','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='31'),'上海市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='32'),'南京市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='32'),'无锡市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='32'),'徐州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='32'),'常州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='32'),'苏州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='32'),'南通市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='32'),'连云港市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='32'),'淮安市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='32'),'盐城市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='32'),'扬州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='32'),'镇江市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='32'),'泰州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='32'),'宿迁市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='33'),'杭州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='33'),'宁波市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='33'),'温州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='33'),'嘉兴市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='33'),'湖州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='33'),'绍兴市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='33'),'金华市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='33'),'衢州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='33'),'舟山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='33'),'台州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='33'),'丽水市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='34'),'合肥市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='34'),'芜湖市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='34'),'蚌埠市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='34'),'淮南市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='34'),'马鞍山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='34'),'淮北市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='34'),'铜陵市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='34'),'安庆市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='34'),'黄山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='34'),'滁州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='34'),'阜阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='34'),'宿州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='15' and fk_province='34'),'六安市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='16' and fk_province='34'),'亳州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='17' and fk_province='34'),'池州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='18' and fk_province='34'),'宣城市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='35'),'福州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='35'),'厦门市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='35'),'莆田市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='35'),'三明市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='35'),'泉州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='35'),'漳州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='35'),'南平市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='35'),'龙岩市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='35'),'宁德市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='36'),'南昌市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='36'),'景德镇市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='36'),'萍乡市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='36'),'九江市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='36'),'新余市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='36'),'鹰潭市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='36'),'赣州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='36'),'吉安市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='36'),'宜春市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='36'),'抚州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='36'),'上饶市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='37'),'济南市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='37'),'青岛市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='37'),'淄博市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='37'),'枣庄市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='37'),'东营市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='37'),'烟台市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='37'),'潍坊市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='37'),'济宁市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='37'),'泰安市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='37'),'威海市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='37'),'日照市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='37'),'临沂市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='14' and fk_province='37'),'德州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='15' and fk_province='37'),'聊城市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='16' and fk_province='37'),'滨州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='17' and fk_province='37'),'菏泽市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='41'),'郑州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='41'),'开封市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='41'),'洛阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='41'),'平顶山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='41'),'安阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='41'),'鹤壁市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='41'),'新乡市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='41'),'焦作市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='41'),'濮阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='41'),'许昌市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='41'),'漯河市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='41'),'三门峡市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='41'),'南阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='14' and fk_province='41'),'商丘市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='15' and fk_province='41'),'信阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='16' and fk_province='41'),'周口市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='17' and fk_province='41'),'驻马店市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='90' and fk_province='41'),'省直辖县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='42'),'武汉市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='42'),'黄石市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='42'),'十堰市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='42'),'宜昌市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='42'),'襄阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='42'),'鄂州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='42'),'荆门市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='42'),'孝感市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='42'),'荆州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='42'),'黄冈市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='42'),'咸宁市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='42'),'随州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='28' and fk_province='42'),'恩施土家族苗族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='90' and fk_province='42'),'省直辖县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='43'),'长沙市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='43'),'株洲市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='43'),'湘潭市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='43'),'衡阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='43'),'邵阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='43'),'岳阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='43'),'常德市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='43'),'张家界市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='43'),'益阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='43'),'郴州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='43'),'永州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='43'),'怀化市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='43'),'娄底市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='31' and fk_province='43'),'湘西土家族苗族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='44'),'广州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='44'),'韶关市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='44'),'深圳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='44'),'珠海市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='44'),'汕头市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='44'),'佛山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='44'),'江门市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='44'),'湛江市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='44'),'茂名市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='44'),'肇庆市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='44'),'惠州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='14' and fk_province='44'),'梅州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='15' and fk_province='44'),'汕尾市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='16' and fk_province='44'),'河源市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='17' and fk_province='44'),'阳江市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='18' and fk_province='44'),'清远市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='19' and fk_province='44'),'东莞市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='20' and fk_province='44'),'中山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='51' and fk_province='44'),'潮州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='52' and fk_province='44'),'揭阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='53' and fk_province='44'),'云浮市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='45'),'南宁市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='45'),'柳州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='45'),'桂林市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='45'),'梧州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='45'),'北海市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='45'),'防城港市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='45'),'钦州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='45'),'贵港市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='45'),'玉林市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='45'),'百色市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='45'),'贺州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='45'),'河池市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='45'),'来宾市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='14' and fk_province='45'),'崇左市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='46'),'海口市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='46'),'三亚市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='46'),'三沙市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='46'),'儋州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='90' and fk_province='46'),'省直辖县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='50'),'重庆市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='50'),'县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='51'),'成都市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='51'),'自贡市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='51'),'攀枝花市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='51'),'泸州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='51'),'德阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='51'),'绵阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='51'),'广元市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='51'),'遂宁市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='51'),'内江市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='51'),'乐山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='51'),'南充市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='14' and fk_province='51'),'眉山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='15' and fk_province='51'),'宜宾市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='16' and fk_province='51'),'广安市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='17' and fk_province='51'),'达州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='18' and fk_province='51'),'雅安市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='19' and fk_province='51'),'巴中市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='20' and fk_province='51'),'资阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='32' and fk_province='51'),'阿坝藏族羌族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='33' and fk_province='51'),'甘孜藏族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='34' and fk_province='51'),'凉山彝族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='52'),'贵阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='52'),'六盘水市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='52'),'遵义市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='52'),'安顺市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='52'),'毕节市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='52'),'铜仁市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='23' and fk_province='52'),'黔西南布依族苗族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='26' and fk_province='52'),'黔东南苗族侗族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='27' and fk_province='52'),'黔南布依族苗族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='53'),'昆明市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='53'),'曲靖市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='53'),'玉溪市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='53'),'保山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='53'),'昭通市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='53'),'丽江市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='53'),'普洱市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='53'),'临沧市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='23' and fk_province='53'),'楚雄彝族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='25' and fk_province='53'),'红河哈尼族彝族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='26' and fk_province='53'),'文山壮族苗族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='28' and fk_province='53'),'西双版纳傣族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='29' and fk_province='53'),'大理白族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='31' and fk_province='53'),'德宏傣族景颇族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='33' and fk_province='53'),'怒江傈僳族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='34' and fk_province='53'),'迪庆藏族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='54'),'拉萨市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='54'),'日喀则市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='54'),'昌都市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='54'),'林芝市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='54'),'山南市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='54'),'那曲市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='25' and fk_province='54'),'阿里地区','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='61'),'西安市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='61'),'铜川市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='61'),'宝鸡市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='61'),'咸阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='61'),'渭南市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='61'),'延安市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='61'),'汉中市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='61'),'榆林市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='61'),'安康市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='61'),'商洛市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='62'),'兰州市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='62'),'嘉峪关市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='62'),'金昌市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='62'),'白银市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='62'),'天水市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='62'),'武威市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='62'),'张掖市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='62'),'平凉市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='62'),'酒泉市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='10' and fk_province='62'),'庆阳市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='62'),'定西市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='62'),'陇南市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='29' and fk_province='62'),'临夏回族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='30' and fk_province='62'),'甘南藏族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='63'),'西宁市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='63'),'海东市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='22' and fk_province='63'),'海北藏族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='23' and fk_province='63'),'黄南藏族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='25' and fk_province='63'),'海南藏族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='26' and fk_province='63'),'果洛藏族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='27' and fk_province='63'),'玉树藏族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='28' and fk_province='63'),'海西蒙古族藏族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='64'),'银川市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='64'),'石嘴山市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='64'),'吴忠市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='64'),'固原市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='64'),'中卫市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='65'),'乌鲁木齐市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='65'),'克拉玛依市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='65'),'吐鲁番市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='65'),'哈密市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='23' and fk_province='65'),'昌吉回族自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='27' and fk_province='65'),'博尔塔拉蒙古自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='28' and fk_province='65'),'巴音郭楞蒙古自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='29' and fk_province='65'),'阿克苏地区','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='30' and fk_province='65'),'克孜勒苏柯尔克孜自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='31' and fk_province='65'),'喀什地区','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='32' and fk_province='65'),'和田地区','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='40' and fk_province='65'),'伊犁哈萨克自治州','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='42' and fk_province='65'),'塔城地区','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='43' and fk_province='65'),'阿勒泰地区','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='90' and fk_province='65'),'自治区直辖县级行政区划','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='71'),'台北市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='71'),'高雄市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='71'),'台南市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='04' and fk_province='71'),'台中市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='05' and fk_province='71'),'金门县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='06' and fk_province='71'),'南投县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='07' and fk_province='71'),'基隆市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='08' and fk_province='71'),'新竹市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='09' and fk_province='71'),'嘉义市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='11' and fk_province='71'),'新北市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='12' and fk_province='71'),'宜兰县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='13' and fk_province='71'),'新竹县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='14' and fk_province='71'),'桃园市','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='15' and fk_province='71'),'苗栗县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='17' and fk_province='71'),'彰化县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='19' and fk_province='71'),'嘉义县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='21' and fk_province='71'),'云林县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='24' and fk_province='71'),'屏东县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='25' and fk_province='71'),'台东县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='26' and fk_province='71'),'花莲县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='27' and fk_province='71'),'澎湖县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='28' and fk_province='71'),'连江县','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='81'),'香港岛','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='81'),'九龙','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='03' and fk_province='81'),'新界','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='01' and fk_province='82'),'澳门半岛','chinese');
INSERT INTO `suzz-mini`.`city_lang`(`fk_city`,`name`,`lang`) VALUES ((select id from `suzz-mini`.`city` where code='02' and fk_province='82'),'离岛','chinese');