INSERT INTO `suzz-mini`.`province`(`id`) VALUES (11);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (12);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (13);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (14);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (15);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (21);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (22);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (23);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (31);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (32);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (33);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (34);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (35);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (36);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (37);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (41);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (42);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (43);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (44);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (45);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (46);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (50);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (51);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (52);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (53);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (54);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (61);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (62);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (63);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (64);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (65);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (71);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (81);
INSERT INTO `suzz-mini`.`province`(`id`) VALUES (82);

INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (11, '北京市', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (12, '天津市', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (13, '河北省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (14, '山西省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (15, '内蒙古自治区', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (21, '辽宁省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (22, '吉林省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (23, '黑龙江省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (31, '上海市', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (32, '江苏省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (33, '浙江省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (34, '安徽省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (35, '福建省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (36, '江西省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (37, '山东省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (41, '河南省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (42, '湖北省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (43, '湖南省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (44, '广东省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (45, '广西壮族自治区', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (46, '海南省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (50, '重庆市', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (51, '四川省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (52, '贵州省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (53, '云南省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (54, '西藏自治区', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (61, '陕西省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (62, '甘肃省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (63, '青海省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (64, '宁夏回族自治区', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (65, '新疆维吾尔自治区', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (71, '台湾省', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (81, '香港特别行政区', 'chinese');
INSERT INTO `suzz-mini`.`province_lang`(`fk_province`, `name`, `lang`) VALUES (82, '澳门特别行政区', 'chinese');
