server:
  port: 8071
  servlet:
    context-path: /mini/facade
spring:
  application:
    name: suzz-mini-facade
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      connection-properties: config.decrypt=false;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAICh7yR0U9fwhyhNxqwASpY43wHMQeT81StZ8cf39rVHtPnoo3DV2ILrw1Km4wAJKEKxIj84VvrvzdSobwZPPJMCAwEAAQ==
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
          db-type: mysql
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: weimeng
        allow:
      aop-patterns: com.suzz.mini.application.*Service.*
  cache:
    type: redis
management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0 # 逻辑已删除值(默认为 0)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 1)
  configuration:
    # 二级缓存
    cache-enabled: true
    # 懒加载开关
    lazy-loading-enabled: false
  # Mapper 所对应的 XML 文件位置
  mapper-locations:
    - classpath*:mapper/**/*Mapper.xml
dubbo:
  application:
    name: suzz-mini-facade
    version: 1.0
    logger: slf4j
    qos-enable: false
    qos-port: 26105
  protocol:
    name: dubbo
    port: 26005
  registry:
    protocol: zookeeper
    file: dubbo-registry-mini-facade.properties
  consumer:
    check: false
  dropdown:
    group: mini