info:
  version: V20221216-UAT
dubbo:
  registry:
    address: xxx.xxx.xxx.xxx:xxx
    default: true
  metadata-report:
    address: zookeeper://xxx.xxx.xxx.xxx:2181
spring:
  datasource:
    name: szwl-mini
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/suzz-mini?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx
  redis:
    host: xxx.xxx.xxx.xxx
    port: 6379
    database: 1
  boot:
    admin:
      client:
        enabled: true
        url: "http://xxx.xxx.xxx.xxx:8082"
        instance:
          name: suzz-mini-facade
          service-base-url: http://xxx.xxx.xxx.xxx:${server.port}
        username: admin
        password: weimeng
logging:
  file: /suzz/mini-facade.log


